name: Build & Deploy All Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout all-docs
      uses: actions/checkout@v3

    - name: Clone ffxiv-raid-sim Docs
      run: |
        git clone --depth=1 https://github.com/susy-bakaa/ffxiv-raid-sim.git
        cd ffxiv-raid-sim/docs

        # Install MkDocs
        pip install mkdocs-material

        # Build the site
        mkdocs build --site-dir ../../../raidsim

    - name: Prepare Deploy Directory
      run: |
        mkdir -p public
        cp -r raidsim public/raidsim
        echo "docs.susybaka.dev" > public/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
